version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    resource_class: small
    steps:
      # DEFINE HERE YOUR TESTS AND ARTIFACTS
      - checkout
      - aws-s3/copy:
          from: README.md
          to: 's3://kelsus-cdk/$(cat package.json | jq "(.version)" --raw-output)-test/kelsus-cdk'
